## Fibonacci Recursive:
### Time: $\mathcal{O}(2^{n})$
### Space: $\mathcal{O}(n)$

In [48]:
def fib(n):
    if n<=2:
        return 1
    return fib(n-1) + fib(n-2)
fib(6)

8

### Fibonacci Recursive Memoization
### Time: $\mathcal{O}({n})$
### Space: $\mathcal{O}(n)$

In [19]:
memo = [0]*200000
def dm_fib(n):
    if memo[n] != 0: return memo[n]
    if n<=2:
        memo[n]=1
    else:
        memo[n] = dm_fib(n-1) + dm_fib(n-2)
    return memo[n]
fib(50)

12586269025

## Bottom-Up Fibonacci

In [49]:
memo = [0]*2000
memo[0] = 1
memo[1] = 1

def bt_fib(n):
    global memo
    if n<=2:
        return memo[n-1]
    else:
        for i in range(2,n+1):
            memo[i-1] = memo[i-2] + memo[i-3]
    return memo[n-1]
bt_fib(50)

12586269025

## Problem:
#### Time:$\mathcal{O}(2^{n+m})$

Say that you are  a traveler on a 2D grid. You begin in the top-left corner and your goal is to travel to the bottom-right corner. You may only move down or right. In how many ways can you travel to the goal on a grid with dimensions $m²$

In [6]:
#grid traveler
import numpy as np
X = np.ndarray(shape=[3,3])
print(X)
def gt(n,m):
    if n == 1 and m==1: return 1
    if n <= 0 or m <= 0: return 0
    else:
        return gt(n-1,m) + gt(n,m-1)
gt(2,3)


[[4.65919205e-310 0.00000000e+000 6.79038654e-313]
 [2.22809558e-312 2.14321575e-312 2.46151512e-312]
 [2.41907520e-312 5.97819431e-322 3.95252517e-322]]


3